name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build-package:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies for build
        run: pip install wheel
      - name: Build package
        run: python3 setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: pip-build
          path: dist

  push_test_pip:
    environment: production
    needs: [build-package]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: actions/download-artifact@v2
        with:
          name: pip-build
          path: dist
      - name: Install dependencies to deploy
        run: pip install twine
      - name: Deploy to test.pypi
        run: echo "$PYPIRC" | base64 -d > .pypirc && python3 -m twine upload --repository testpypi dist/*

  push_pip:
    environment: production
    needs: [build-package]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: actions/download-artifact@v2
        with:
          name: pip-build
          path: dist
      - name: Install dependencies to deploy
        run: pip install twine
      - name: Deploy to test.pypi
        run: echo "$PYPIRC" | base64 -d > .pypirc && python3 -m twine upload --repository pypi dist/*
